FROM python:3.9

ENV PORT=8000

WORKDIR /code

ENV MODEL_TYPE="pytorch"
COPY ./main.py /code/
COPY ./server /code/server
COPY ./requirements.txt /code/requirements.txt
COPY ./model.pt /code/model.pt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

ENV MODEL_PATH="/code/model.pt"

CMD ["python3", "main.py"]